from google.cloud.bigquery import SchemaField

schema_obt_players = [
    SchemaField('team_id', 'STRING', mode='NULLABLE'),
    SchemaField('team_name', 'STRING', mode='NULLABLE'),
    SchemaField('fixture', 'INTEGER', mode='NULLABLE'),
    SchemaField('player_id', 'STRING', mode='NULLABLE'),
    SchemaField('player_name', 'STRING', mode='NULLABLE'),
    SchemaField('statistics_games_minutes', 'STRING', mode='NULLABLE'),
    SchemaField('statistics_games_number', 'STRING', mode='NULLABLE'),
    SchemaField('statistics_games_position', 'STRING', mode='NULLABLE'),
    SchemaField('statistics_games_rating', 'STRING', mode='NULLABLE'),
    SchemaField('statistics_games_captain', 'STRING', mode='NULLABLE'),
    SchemaField('statistics_games_substitute', 'STRING', mode='NULLABLE'),
    SchemaField('statistics_offsides', 'STRING', mode='NULLABLE'),
    SchemaField('statistics_shots_total', 'STRING', mode='NULLABLE'),
    SchemaField('statistics_shots_on', 'STRING', mode='NULLABLE'),
    SchemaField('statistics_goals_total', 'STRING', mode='NULLABLE'),
    SchemaField('statistics_goals_conceded', 'STRING', mode='NULLABLE'),
    SchemaField('statistics_goals_assists', 'STRING', mode='NULLABLE'),
    SchemaField('statistics_goals_saves', 'STRING', mode='NULLABLE'),
    SchemaField('statistics_passes_total', 'STRING', mode='NULLABLE'),
    SchemaField('statistics_passes_key', 'STRING', mode='NULLABLE'),
    SchemaField('statistics_passes_accuracy', 'STRING', mode='NULLABLE'),
    SchemaField('statistics_tackles_total', 'STRING', mode='NULLABLE'),
    SchemaField('statistics_tackles_blocks', 'STRING', mode='NULLABLE'),
    SchemaField('statistics_tackles_interceptions', 'STRING', mode='NULLABLE'),
    SchemaField('statistics_duels_total', 'STRING', mode='NULLABLE'),
    SchemaField('statistics_duels_won', 'STRING', mode='NULLABLE'),
    SchemaField('statistics_dribbles_attempts', 'STRING', mode='NULLABLE'),
    SchemaField('statistics_dribbles_success', 'STRING', mode='NULLABLE'),
    SchemaField('statistics_dribbles_past', 'STRING', mode='NULLABLE'),
    SchemaField('statistics_fouls_drawn', 'STRING', mode='NULLABLE'),
    SchemaField('statistics_fouls_committed', 'STRING', mode='NULLABLE'),
    SchemaField('statistics_cards_yellow', 'STRING', mode='NULLABLE'),
    SchemaField('statistics_cards_red', 'STRING', mode='NULLABLE'),
    SchemaField('statistics_penalty_won', 'STRING', mode='NULLABLE'),
    SchemaField('statistics_penalty_commited', 'STRING', mode='NULLABLE'),
    SchemaField('statistics_penalty_scored', 'STRING', mode='NULLABLE'),
    SchemaField('statistics_penalty_missed', 'STRING', mode='NULLABLE'),
    SchemaField('statistics_penalty_saved', 'STRING', mode='NULLABLE'),
    SchemaField('match_id', 'INTEGER', mode='NULLABLE'),
    SchemaField('date', 'STRING', mode='NULLABLE'),
    SchemaField('reference_date', 'STRING', mode='NULLABLE'),
    SchemaField('round', 'STRING', mode='NULLABLE'),
    SchemaField('league_id', 'INTEGER', mode='NULLABLE'),
    SchemaField('id_team_away', 'INTEGER', mode='NULLABLE'),
    SchemaField('id_team_home', 'INTEGER', mode='NULLABLE'),
    SchemaField('goals_home', 'INTEGER', mode='NULLABLE'),
    SchemaField('goals_away', 'INTEGER', mode='NULLABLE'),
    SchemaField('winner_home', 'BOOLEAN', mode='NULLABLE'),
    SchemaField('winner_away', 'BOOLEAN', mode='NULLABLE'),
]

schema_obt_matches = [
    SchemaField('match_id', 'INTEGER'),
    SchemaField('date', 'STRING'),
    SchemaField('reference_date', 'STRING'),
    SchemaField('round', 'STRING'),
    SchemaField('league_id', 'INTEGER'),
    SchemaField('id_team_away', 'INTEGER'),
    SchemaField('id_team_home', 'INTEGER'),
    SchemaField('goals_home', 'INTEGER'),
    SchemaField('goals_away', 'INTEGER'),
    SchemaField('winner_home', 'BOOLEAN'),
    SchemaField('winner_away', 'BOOLEAN'),
    SchemaField('statistics_ShotsonGoal', 'FLOAT'),
    SchemaField('statistics_ShotsoffGoal', 'FLOAT'), # Bug do bigquery
    SchemaField('statistics_TotalShots', 'INTEGER'),
    SchemaField('statistics_BlockedShots', 'FLOAT'),
    SchemaField('statistics_Shotsinsidebox', 'FLOAT'),
    SchemaField('statistics_Shotsoutsidebox', 'FLOAT'),
    SchemaField('statistics_Fouls', 'INTEGER'),
    SchemaField('statistics_CornerKicks', 'FLOAT'),
    SchemaField('statistics_Offsides', 'FLOAT'),
    SchemaField('statistics_BallPossession', 'FLOAT'),
    SchemaField('statistics_YellowCards', 'FLOAT'),
    SchemaField('statistics_RedCards', 'FLOAT'),
    SchemaField('statistics_GoalkeeperSaves', 'FLOAT'),
    SchemaField('statistics_Totalpasses', 'INTEGER'),
    SchemaField('statistics_Passesaccurate', 'INTEGER'),
    SchemaField('statistics_Passesperc', 'FLOAT'),
    SchemaField('team_id', 'INTEGER'), # Bug do bigquery
    SchemaField('fixture', 'INTEGER'),
    SchemaField('name', 'STRING'),
    SchemaField('code', 'STRING'),
    SchemaField('country', 'STRING'),
    SchemaField('logo', 'STRING'),
    SchemaField('city', 'STRING'),
    SchemaField('state', 'STRING'),
    SchemaField('home', 'BOOLEAN'),
]
