name: Deploy Cloud Run

on:
  workflow_run:
    workflows: [ Delete Cloud Run ]
    types:
      - completed

env:
  PROJECT_ID: cartola-360814
  REGION: us-east1
  GAR_LOCATION: us-east1-docker.pkg.dev/cartola-360814/cartola-project/cartola-python

jobs:
  tags_versions:
    runs-on: ubuntu-latest
    outputs:
      tag_matchs-teams: ${{ steps.matchs-teams.outputs.tag }}
      tag_obt: ${{ steps.obt.outputs.tag }}
      tag_players_statistics: ${{ steps.players-statistics.outputs.tag }}
    steps:
      - id: github-sha
        run: |-
          echo "VERSION=$(echo $(date +'%Y%m%d'))" >> $GITHUB_ENV
      - id: matchs-teams
        env:
          TYPE: matchs-teams
        run: echo "tag=${{ env.GAR_LOCATION }}-${{ env.TYPE }}:$VERSION" >> $GITHUB_OUTPUT
      - id: players-statistics
        env:
          TYPE: players-statistics
        run: echo "tag=${{ env.GAR_LOCATION }}-${{ env.TYPE }}:$VERSION" >> $GITHUB_OUTPUT
  cloud_run:
    runs-on: ubuntu-latest
    needs: [ tags_versions ]
    strategy:
      matrix:
        include:
          - IMG: ${{ needs.tags_versions.outputs.tag_players_statistics }}
            LEAGUE_ID: 71
            SEASON_YEAR: 2024
            TYPE: players-statistics
            ORIGIN: brasil
          - IMG: ${{ needs.tags_versions.outputs.tag_matchs-teams }}
            LEAGUE_ID: 71
            SEASON_YEAR: 2024
            TYPE: matchs-teams
            ORIGIN: brasil
          - IMG: ${{ needs.tags_versions.outputs.tag_players_statistics }}
            LEAGUE_ID: 39_78
            SEASON_YEAR: 2024
            TYPE: players-statistics
            ORIGIN: europa
          - IMG: ${{ needs.tags_versions.outputs.tag_matchs-teams }}
            LEAGUE_ID: 39_78
            SEASON_YEAR: 2024
            TYPE: matchs-teams
            ORIGIN: europa
    steps:
      - id: "Auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - id: "Deploy"
        run: |-
          gcloud run jobs create ${{ matrix.TYPE }}-${{ matrix.ORIGIN }} \
            --image=${{ matrix.IMG }} \
            --service-account=${{ vars.SERVICE_ACCOUNT }} \
            --set-env-vars=API_HOST_KEY=${{ secrets.API_HOST_KEY }},LEAGUE_ID=${{ matrix.LEAGUE_ID }},SEASON_YEAR=${{ matrix.SEASON_YEAR }} \
            --set-secrets=API_SECERT_KEY=Rapid_Api_API_SECERT_KEY:1 \
            --region=${{ env.REGION }} \
            --project=${{ env.PROJECT_ID }} \
            --tasks=1 \
            --max-retries=2 \
            --parallelism=1