name: Deploy Cloud Run

on:
  workflow_run:
    workflows: [ Build and Push to Artifact Registry Geral ]
    types:
      - completed

env:
  PROJECT_ID: cartola-360814
  REGION: us-east1
  GAR_LOCATION: us-east1-docker.pkg.dev/cartola-360814/cartola-project/cartola-python

jobs:
  tags_versions:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      tag_matchs-teams: ${{ steps.matchs-teams.outputs.tag }}
      tag_obt: ${{ steps.obt.outputs.tag }}
      tag_players: ${{ steps.players.outputs.tag }}
      tag_statistics: ${{ steps.statistics.outputs.tag }}
    steps:
      - id: matchs-teams
        env:
          TYPE: matchs-teams
        run: echo "tag=${{ env.GAR_LOCATION }}-${{ env.TYPE }}:$(git rev-parse --short HEAD)" >> $GITHUB_ENV >> $GITHUB_OUTPUT
      - id: obt
        env:
          TYPE: obt
        run: echo "tag=${{ env.GAR_LOCATION }}-${{ env.TYPE }}:$(git rev-parse --short HEAD)" >> $GITHUB_ENV >> $GITHUB_OUTPUT
      - id: players
        env:
          TYPE: players
        run: echo "tag=${{ env.GAR_LOCATION }}-${{ env.TYPE }}:$(git rev-parse --short HEAD)" >> $GITHUB_ENV >> $GITHUB_OUTPUT
      - id: statistics
        env:
          TYPE: statistics
        run: echo "tag=${{ env.GAR_LOCATION }}-${{ env.TYPE }}:$(git rev-parse --short HEAD)" >> $GITHUB_ENV >> $GITHUB_OUTPUT
  cloud-run_players:
    runs-on: ubuntu-latest
    needs: [ tags_versions ]
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - id: "Auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Cloud Run Deploy Jobs da Liga 71"
        env:
          IMG: ${{needs.tags_versions.outputs.tag_matchs-teams}}
        run: |-
          gcloud run jobs create partidas-71 \
                --image=${{ env.IMG }} \
                --service-account=${{ vars.SERVICE_ACCOUNT }} \
                --set-env-vars=API_HOST_KEY=${{ secrets.API_HOST_KEY }},API_SECERT_KEY=${{ secrets.API_SECERT_KEY }},LEAGUE_ID=71,SEASON_YEAR=2023 \
                --region=us-central1 \
                --project=cartola-360814 \
                --tasks=1 \
                --max-retries=2 \
                --parallelism=1

      - name: "Cloud Run Deploy Jobs da Liga 39"
        env:
          IMG: ${{needs.tags_versions.outputs.tag_matchs-teams}}
        run: |-
          gcloud run jobs create partidas-39 \
                --image=${{ env.IMG }} \
                --service-account=${{ vars.SERVICE_ACCOUNT }} \
                --set-env-vars=API_HOST_KEY=${{ secrets.API_HOST_KEY }},API_SECERT_KEY=${{ secrets.API_SECERT_KEY }},LEAGUE_ID=39,SEASON_YEAR=2023 \
                --region=us-central1 \
                --project=cartola-360814 \
                --tasks=1 \
                --max-retries=2 \
                --parallelism=1
  cloud-run_teams:
    runs-on: ubuntu-latest
    needs: [ tags_versions, docker-matchs-teams, docker-players, docker-obt, docker-statistics ]
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - id: "Auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Cloud Run Deploy Jobs da Liga 71"
        env:
          IMG: ${{needs.tags_versions.outputs.tag_matchs-teams}}
        run: |-
          gcloud run jobs create partidas-71 \
                --image=${{ env.IMG }} \
                --service-account=${{ vars.SERVICE_ACCOUNT }} \
                --set-env-vars=API_HOST_KEY=${{ secrets.API_HOST_KEY }},API_SECERT_KEY=${{ secrets.API_SECERT_KEY }},LEAGUE_ID=71,SEASON_YEAR=2023 \
                --region=us-central1 \
                --project=cartola-360814 \
                --tasks=1 \
                --max-retries=2 \
                --parallelism=1

      - name: "Cloud Run Deploy Jobs da Liga 39"
        env:
          IMG: ${{needs.tags_versions.outputs.tag_matchs-teams}}
        run: |-
          gcloud run jobs create partidas-39 \
                --image=${{ env.IMG }} \
                --service-account=${{ vars.SERVICE_ACCOUNT }} \
                --set-env-vars=API_HOST_KEY=${{ secrets.API_HOST_KEY }},API_SECERT_KEY=${{ secrets.API_SECERT_KEY }},LEAGUE_ID=39,SEASON_YEAR=2023 \
                --region=us-central1 \
                --project=cartola-360814 \
                --tasks=1 \
                --max-retries=2 \
                --parallelism=1
  cloud-run_stats:
    runs-on: ubuntu-latest
    needs: [ tags_versions, docker-matchs-teams, docker-players, docker-obt, docker-statistics ]
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - id: "Auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Cloud Run Deploy Jobs da Liga 71"
        env:
          IMG: ${{needs.tags_versions.outputs.tag_matchs-teams}}
        run: |-
          gcloud run jobs create partidas-71 \
                --image=${{ env.IMG }} \
                --service-account=${{ vars.SERVICE_ACCOUNT }} \
                --set-env-vars=API_HOST_KEY=${{ secrets.API_HOST_KEY }},API_SECERT_KEY=${{ secrets.API_SECERT_KEY }},LEAGUE_ID=71,SEASON_YEAR=2023 \
                --region=us-central1 \
                --project=cartola-360814 \
                --tasks=1 \
                --max-retries=2 \
                --parallelism=1

      - name: "Cloud Run Deploy Jobs da Liga 39"
        env:
          IMG: ${{needs.tags_versions.outputs.tag_matchs-teams}}
        run: |-
          gcloud run jobs create partidas-39 \
                --image=${{ env.IMG }} \
                --service-account=${{ vars.SERVICE_ACCOUNT }} \
                --set-env-vars=API_HOST_KEY=${{ secrets.API_HOST_KEY }},API_SECERT_KEY=${{ secrets.API_SECERT_KEY }},LEAGUE_ID=39,SEASON_YEAR=2023 \
                --region=us-central1 \
                --project=cartola-360814 \
                --tasks=1 \
                --max-retries=2 \
                --parallelism=1
  cloud-run_obt:
    runs-on: ubuntu-latest
    needs: [ tags_versions, docker-matchs-teams, docker-players, docker-obt, docker-statistics ]
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - id: "Auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Cloud Run Deploy Jobs da Liga 71"
        env:
          IMG: ${{needs.tags_versions.outputs.tag_matchs-teams}}
        run: |-
          gcloud run jobs create partidas-71 \
                --image=${{ env.IMG }} \
                --service-account=${{ vars.SERVICE_ACCOUNT }} \
                --set-env-vars=API_HOST_KEY=${{ secrets.API_HOST_KEY }},API_SECERT_KEY=${{ secrets.API_SECERT_KEY }},LEAGUE_ID=71,SEASON_YEAR=2023 \
                --region=us-central1 \
                --project=cartola-360814 \
                --tasks=1 \
                --max-retries=2 \
                --parallelism=1

      - name: "Cloud Run Deploy Jobs da Liga 39"
        env:
          IMG: ${{needs.tags_versions.outputs.tag_matchs-teams}}
        run: |-
          gcloud run jobs create partidas-39 \
                --image=${{ env.IMG }} \
                --service-account=${{ vars.SERVICE_ACCOUNT }} \
                --set-env-vars=API_HOST_KEY=${{ secrets.API_HOST_KEY }},API_SECERT_KEY=${{ secrets.API_SECERT_KEY }},LEAGUE_ID=39,SEASON_YEAR=2023 \
                --region=us-central1 \
                --project=cartola-360814 \
                --tasks=1 \
                --max-retries=2 \
                --parallelism=1
