name: Delete Cloud Run

on:
  workflow_run:
    workflows: [ Build and Push to Artifact Registry Geral ]
    types:
      - completed

env:
  PROJECT_ID: cartola-360814
  REGION: us-east1
  GAR_LOCATION: us-east1-docker.pkg.dev/cartola-360814/cartola-project/cartola-python

jobs:
  cloud_run:
    if: |
      ${{ github.event.workflow_run.conclusion == 'success' && !contains(github.base_ref, 'league') }}
    strategy:
      matrix:
        cloud_run: [players-statistics-71, matchs-teams-71, players-statistics-39, matchs-teams-39, players-statistics-78, matchs-teams-78, obt-geral]
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - id: "Auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Delete Cloud Run"
        run: |-
          gcloud run jobs delete ${{ matrix.cloud_run }} --region ${{ env.REGION }} --quiet 
