name: Build and Push to Artifact Registry Geral

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PROJECT_ID: cartola-360814
  REGION: us-east1
  GAR_LOCATION: us-east1-docker.pkg.dev/cartola-360814/cartola-project/cartola-python

jobs:
  tags_versions:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      tag_matchs-teams: ${{ steps.matchs-teams.outputs.tag }}
      tag_obt: ${{ steps.obt.outputs.tag }}
      tag_players: ${{ steps.players.outputs.tag }}
      tag_statistics: ${{ steps.statistics.outputs.tag }}
    steps:
      - id: matchs-teams
        env:
          TYPE: matchs-teams
        run: echo "tag=${{ env.GAR_LOCATION }}-${{ env.TYPE }}:${{ github.sha }}" >> $GITHUB_ENV >> $GITHUB_OUTPUT
      - id: obt
        env:
          TYPE: obt
        run: echo "tag=${{ env.GAR_LOCATION }}-${{ env.TYPE }}:${{ github.sha }}" >> $GITHUB_ENV >> $GITHUB_OUTPUT
      - id: players
        env:
          TYPE: players
        run: echo "tag=${{ env.GAR_LOCATION }}-${{ env.TYPE }}:${{ github.sha }}" >> $GITHUB_ENV >> $GITHUB_OUTPUT
      - id: statistics
        env:
          TYPE: statistics
        run: echo "tag=${{ env.GAR_LOCATION }}-${{ env.TYPE }}:${{ github.sha }}" >> $GITHUB_ENV >> $GITHUB_OUTPUT
  docker-matchs-teams:
    runs-on: ubuntu-latest
    needs: tags_versions

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - id: "Auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: "Build image"
        env:
          TYPE: matchs-teams
          MATCHS-TEAMS: ${{needs.tags_versions.outputs.tag_matchs-teams}}
        run: |-
          docker build . --file ./docker_images/${{ env.TYPE }}.Dockerfile \
                         --platform linux/amd64 --tag ${{ env.MATCHS-TEAMS }}

      - name: "Push image"
        env:
          MATCHS-TEAMS: ${{needs.tags_versions.outputs.tag_matchs-teams}}
        run: |-
          docker push ${{ env.MATCHS-TEAMS }}

  docker-players:
    runs-on: ubuntu-latest
    needs: tags_versions

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - id: "Auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: "Build image"
        env:
          TYPE: players
          PLAYERS: ${{needs.tags_versions.outputs.tag_players}}
        run: |-
          docker build . --file ./docker_images/${{ env.TYPE }}.Dockerfile \
                         --platform linux/amd64 --tag ${{ env.PLAYERS }}

      - name: "Push image"
        env:
          TYPE: players
          PLAYERS: ${{needs.tags_versions.outputs.tag_players}}
        run: |-
          docker push ${{ env.PLAYERS }}

  docker-obt:
    runs-on: ubuntu-latest
    needs: tags_versions

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - id: "Auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: "Build image"
        env:
          TYPE: obt
          OBT: ${{needs.tags_versions.outputs.tag_obt}}
        run: |-
          docker build . --file ./docker_images/${{ env.TYPE }}.Dockerfile \
                         --platform linux/amd64 --tag ${{ env.OBT }}

      - name: "Push image"
        env:
          OBT: ${{needs.tags_versions.outputs.tag_obt}}
        run: |-
          docker push ${{ env.OBT }}

  docker-statistics:
    runs-on: ubuntu-latest
    needs: tags_versions

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - id: "Auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: "Build image"
        env:
          TYPE: statistics
          STATISTICS: ${{needs.tags_versions.outputs.tag_statistics}}
        run: |-
          docker build . --file ./docker_images/${{ env.TYPE }}.Dockerfile \
                         --platform linux/amd64 --tag ${{ env.STATISTICS }}

      - name: "Push image"
        env:
          STATISTICS: ${{needs.tags_versions.outputs.tag_statistics}}
        run: |-
          docker push ${{ env.STATISTICS }}
