name: Build and Push to Artifact Registry Geral

on:
  pull_request:
    branches:
      - 'main'

env:
  PROJECT_ID: cartola-360814
  REGION: us-east1
  GAR_LOCATION: us-east1-docker.pkg.dev/cartola-360814/cartola-project/cartola-python

jobs:
  tags_versions:
    runs-on: ubuntu-latest
    outputs:
      tag_matchs-teams: ${{ steps.matchs-teams.outputs.tag }}
      tag_obt: ${{ steps.obt.outputs.tag }}
      tag_players_statistics: ${{ steps.players-statistics.outputs.tag }}
    steps:
      - id: github-sha
        run: |-
          echo "VERSION=$(echo $(date +'%Y%m%d%H%M%S') | sha256sum | awk '{print $1}')" >> $GITHUB_ENV
      - id: matchs-teams
        env:
          TYPE: matchs-teams
        run: echo "tag=${{ env.GAR_LOCATION }}-${{ env.TYPE }}:$VERSION" >> $GITHUB_OUTPUT
      - id: obt
        env:
          TYPE: obt
        run: echo "tag=${{ env.GAR_LOCATION }}-${{ env.TYPE }}:$VERSION" >> $GITHUB_OUTPUT
      - id: players-statistics
        env:
          TYPE: players-statistics
        run: echo "tag=${{ env.GAR_LOCATION }}-${{ env.TYPE }}:$VERSION" >> $GITHUB_OUTPUT
  docker_registry:
    runs-on: ubuntu-latest
    needs: [ tags_versions ]
    strategy:
      max-parallel: 3
      matrix:
        include:
          - IMG: ${{ needs.tags_versions.outputs.tag_players_statistics }}
            TYPE: players-statistics
          - IMG: ${{ needs.tags_versions.outputs.tag_matchs-teams }}
            TYPE: matchs-teams
          - IMG: ${{ needs.tags_versions.outputs.tag_obt}}
            TYPE: obt
    steps:
      - name: "Print variables"
        run: |-
          echo TYPE: ${{ matrix.TYPE }} IMG: ${{ matrix.IMG }}
          

      - name: "Checkout"
        uses: "actions/checkout@v3"

      - id: "Auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: "Build image"
        run: |-
          docker build . --file ./docker_images/${{ matrix.TYPE }}.Dockerfile \
                         --platform linux/amd64 --tag ${{ matrix.IMG }}

      - name: "Push image"
        run: |-
          docker push ${{ matrix.IMG }}
