name: Build and Push to Artifact Registry Geral

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  PROJECT_ID: cartola-360814
  REGION: us-east1
  GAR_LOCATION: us-east1-docker.pkg.dev/cartola-360814/cartola-project/cartola-python

jobs:
  auth:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

  docker-obt:
    runs-on: ubuntu-latest
    needs: auth
    env:
      TYPE: matchs-teams

    steps:
      - name: "Set build version"
        id: set_version
        run: echo "VERSION=$(echo $(date +'%Y%m%d%H%M%S') | sha256sum | awk '{print $1}')" >> $GITHUB_ENV

      - name: "Print folders"
        id: print
        run: ls

      - name: "Build image"
        run: |-
          docker build . --file ./docker_images/${{ env.TYPE }}.Dockerfile \
                         --platform linux/amd64 --tag ${{ env.GAR_LOCATION }}-${{ env.TYPE }}:${{ env.VERSION }}

      - name: "Push image"
        run: |-
          docker push ${{ env.GAR_LOCATION }}-${{ env.TYPE }}:${{ env.VERSION }}

  docker-players:
    runs-on: ubuntu-latest
    needs: auth
    env:
      TYPE: players

    steps:
      - name: "Set build version"
        id: set_version
        run: echo "VERSION=$(echo $(date +'%Y%m%d%H%M%S') | sha256sum | awk '{print $1}')" >> $GITHUB_ENV

      - name: "Print folders"
        id: print
        run: ls

      - name: "Build image"
        run: |-
          docker build . --file ./docker_images/${{ env.TYPE }}.Dockerfile \
                         --platform linux/amd64 --tag ${{ env.GAR_LOCATION }}-${{ env.TYPE }}:${{ env.VERSION }}

      - name: "Push image"
        run: |-
          docker push ${{ env.GAR_LOCATION }}-${{ env.TYPE }}:${{ env.VERSION }}