name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [ push ]

env:
  PROJECT_ID: cartola-360814
  REGION: us-east1
  GAR_LOCATION: us-east1-docker.pkg.dev/cartola-360814/cartola-project/cartola-python

jobs:
  tags_versions:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      tag_matchs-teams: ${{ steps.matchs-teams.outputs.tag }}
      tag_obt: ${{ steps.obt.outputs.tag }}
      tag_players: ${{ steps.players.outputs.tag }}
      tag_statistics: ${{ steps.statistics.outputs.tag }}
    steps:
      - id: matchs-teams
        env:
          TYPE: matchs-teams
        run: echo "tag=${{ env.GAR_LOCATION }}-${{ env.TYPE }}:$(echo $(date +'%Y%m%d%H%M%S') | sha256sum | awk '{print $1}')" >> $GITHUB_ENV >> $GITHUB_OUTPUT
      - id: obt
        env:
          TYPE: obt
        run: echo "tag=${{ env.GAR_LOCATION }}-${{ env.TYPE }}:$(echo $(date +'%Y%m%d%H%M%S') | sha256sum | awk '{print $1}')" >> $GITHUB_ENV >> $GITHUB_OUTPUT
      - id: players
        env:
          TYPE: players
        run: echo "tag=${{ env.GAR_LOCATION }}-${{ env.TYPE }}:$(echo $(date +'%Y%m%d%H%M%S') | sha256sum | awk '{print $1}')" >> $GITHUB_ENV >> $GITHUB_OUTPUT
      - id: statistics
        env:
          TYPE: statistics
        run: echo "tag=${{ env.GAR_LOCATION }}-${{ env.TYPE }}:$(echo $(date +'%Y%m%d%H%M%S') | sha256sum | awk '{print $1}')" >> $GITHUB_ENV >> $GITHUB_OUTPUT
  job2:
    runs-on: ubuntu-latest
    needs: tags_versions
    steps:
      - env:
          MATCHS-TEAMS: ${{needs.tags_versions.outputs.tag_matchs-teams}}
          OBT: ${{needs.tags_versions.outputs.tag_obt}}
          PLAYERS: ${{needs.tags_versions.outputs.tag_players}}
          STATISTICS: ${{needs.tags_versions.outputs.tag_statistics}}
        run: echo "${{ env.MATCHS-TEAMS }} \n ${{ env.OBT }} \n ${{ env.PLAYERS }} \n ${{ env.STATISTICS }}"
  job3:
    runs-on: ubuntu-latest
    needs: [ tags_versions, job2 ]
    steps:
      - env:
          MATCHS-TEAMS: ${{needs.tags_versions.outputs.tag_matchs-teams}}
          OBT: ${{needs.tags_versions.outputs.tag_obt}}
          PLAYERS: ${{needs.tags_versions.outputs.tag_players}}
          STATISTICS: ${{needs.tags_versions.outputs.tag_statistics}}
        run: echo "${{ secrets.SERVICE_ACCOUNT }}"
