name: Trigger Jobs using Cron

on:
  workflow_run:
    workflows: [ Deploy Cloud Run ]
    types:
      - completed
env:
  PROJECT_ID: cartola-360814
  REGION: us-east1
  GAR_LOCATION: us-east1-docker.pkg.dev/cartola-360814/cartola-project/cartola-python
jobs:
  triggers-players-stats:
    strategy:
      matrix:
        cloud_run: [ players-stats-71, players-stats-39 ] # incluir obt
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - id: "Auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: "Scheduler matchs-teams 39"
        run: |-
          gcloud scheduler jobs update http ${{ matrix.cloud_run }} \
                  --location ${{ env.REGION }} \
                  --schedule="0 19 * * 1,5" \
                  --uri="https://${{ env.REGION }}-run.googleapis.com/apis/run.googleapis.com/v1/namespaces/cartola-360814/jobs/${{ matrix.cloud_run }}:run" \
                  --http-method POST
  triggers-matchs-teams:
    strategy:
      matrix:
        cloud_run: [ matchs-teams-71, matchs-teams-39 ]
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - id: "Auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: "Scheduler matchs-teams 39"
        run: |-
          gcloud scheduler jobs update http ${{ matrix.cloud_run }} \
                  --location ${{ env.REGION }} \
                  --schedule="0 19 * * 6" \
                  --uri="https://${{ env.REGION }}-run.googleapis.com/apis/run.googleapis.com/v1/namespaces/cartola-360814/jobs/${{ matrix.cloud_run }}:run" \
                  --http-method POST
